### PR TITLE
Added this reference to getInvokingContext

### PR DESCRIPTION
**Pull request by ydarias**
With a grammar like:

```
expr_stmt
  locals [
  symbols: string[] = ['foo'];
  ]
  : leftside=testlist_star_expr ( augassign ( yield_expr | testlist)
                      | ( '=' ( yield_expr| rightside=testlist_star_expr ) )* 
                      ) { console.log(`${$leftside.text} is a ${$rightside.text}`); }
  ;

testlist_star_expr
 : { console.log($expr_stmt::symbols); } ( test | star_expr ) ( ',' ( test |  star_expr ) )* ','? 
 ;
```

an error is thrown, because the method getInvokingContext cannot be found, when using the generated parser. This happens at the TypeScript code, because the translated code is something like:

```
console.log((getInvokingContext(15) as Expr_stmtContext).symbols); 
```

when the valid code should be (by TS "compiler"):

```
console.log((this.getInvokingContext(15) as Expr_stmtContext).symbols); 
```

This pull-request changes the translation code to add the this reference prior to getInvokingContext method.

### CODE REVIEW

**Comment by BurtHarris** [comment]
@ydarias, Thank you for your contribution.
This looks good to me, but I'm really not the expert on the generated code.   
I'd like to see a unit test that demonstrates the problem as well as the fix.
@sharwell Please have a look

**Comment by ydarias** [comment]
@BurtHarris it is a very good idea to create a test. I would like some guidance about that though, because I didn't see tests on the generated code itself. Maybe it is enough to create a test with local elements in the grammar, just like one of the tssoon files has.

It is not a straight way to test it but I think it could work fine, what do you think?

**Comment by BurtHarris** [comment]
Yea, the tests (inherited from a test system built for the Java implementation) are still rather puzzling to me too, particularly those under test/runtime.     I'd suggest we just implement a separate test that somewhat like test/tool/TestTokenStreamReweriter.ts, which does depend on generated code.

**Comment by mike-lischke** [comment]
Most of the Java tests aren't translated to TS yet (see `test/tool`). Should be fairly easy to add a test like [this reference check](https://github.com/tunnelvisionlabs/antlr4ts/blob/master/test/tool/TestParserExec.tssoon#L477) with the code from this PR. The main problem is however that these tests are never executed and would need to be finished first.

**Comment by sharwell** [comment]
> Should be fairly easy to add a test like [this reference check](https://github.com/tunnelvisionlabs/antlr4ts/blob/master/test/tool/TestParserExec.tssoon#L477) with the code from this PR.

@mike-lischke That test was re-implemented in the multi-language test suite here:

https://github.com/tunnelvisionlabs/antlr4/blob/e44c0ec3039bc277c5ad4f06e900d12dc6f3b086/runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/ParserExec/ReferenceToATN.stg
https://github.com/tunnelvisionlabs/antlr4/blob/e44c0ec3039bc277c5ad4f06e900d12dc6f3b086/runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/ParserExec/ReferenceToATN_1.stg
https://github.com/tunnelvisionlabs/antlr4/blob/e44c0ec3039bc277c5ad4f06e900d12dc6f3b086/runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/ParserExec/ReferenceToATN_2.stg

I never went back and removed the original definitions from some of the tests because a number of issues like https://github.com/antlr/antlr4/commit/ae52f2708a93a83639aa1064795602dd3acf9d37 (introduced in https://github.com/antlr/antlr4/commit/86fc7fd44d07d136fed45762a8656ebf407db7c0) left me uncomfortable.

**Comment by ydarias** [comment]
Thank you for the examples, I believe they will help me a lot to build a test for this case :-)

**Comment by BurtHarris** [comment]
Thanks @sharwell, good to see you again.   I think this one is TypeScript specific, it fixes one place in TypeScript.stg where we didn't add an explicit `this.` when porting from Java.

**Comment by ydarias** [comment]
Hi @sharwell, I believe the test is only relevant for TypeScript. The ideal test should check that the generated parser is a valid TypeScript. That means that the code in TS contains the `this` reference. As I see it, it can be done reviewing the generated code itself or using it ... as @mike-lischke signaled before there are some tests in the tool folder that are not completely translated to TS yet, and could be useful in this case.

Since the code that fails is the code in the generated Parser I don't see any other way to test it properly and easy than generating the parser and using it with a known input/output. 

The `BaseTest.tssoon` file contains a way to pass a grammar and generate the Parser and Lexer, I guess, correct me if not. Some examples on how to use it can be find at `TestParserExec.tssoon` too. **Could we use it without too much pain?** The grammar for a test case could contain dynamically-scoped attributes used by some action, so the generated parser should create an expected output. Then not only the expected result is important but the execution itself (that must end without TS errors).

**Comment by sharwell** [comment]
@ydarias I added a test case which revealed a second error. I corrected the error in 8867771.

**Comment by sharwell** [comment]
:memo: my second change ended up getting reverted later. Not sure why the `as` operator was complaining originally but tslint ended up complaining about the angle bracket cast.

**Comment by BurtHarris** [comment]
@sharwell  I had a git glitch that may have been the source of the revert.   See f0593a8806e1ff0f8104ddf9040779a2b502bd26

**Comment by sharwell** [comment]
@BurtHarris I reverted the change as part of the tslint branch.

**Comment by BurtHarris** [comment]
@sharwell OK, I was a bit worried but I came to the conclusion that commit was harmless.   Just wanted to be sure.

**Pull request merged**
