### PR TITLE
Copy README & LICENSE into runtime target dir during build

### LINKED ISSUE #247: Runtime package on NPM is missing readme
See the [antlr4ts](https://www.npmjs.com/package/antlr4ts) package on npmjs.com.

### PR DESCRIPTION
**Pull request by BurtHarris**
This should fix #247, but I won't know for sure till we publish an update to NPM.

### CODE REVIEW

**Comment by sharwell** [comment]
Marking as blocked on #285

**Comment by sharwell** [comment]
Unblocked and restarted the build.

**Comment by BurtHarris** [comment]
Have you figured a way to publish to npm from an Appveyor build?

**Comment by sharwell** [comment]
I haven't looked specifically. I tend to publish locally instead.

**Comment by BurtHarris** [comment]
Punting this because it's languishing...   I'll offer an alternative...

**Pull request closed without merging**
