### PR TITLE
Implement support for optional token and rule getters

### LINKED ISSUE #265: Generated accessors for optional items should allow undefined
As described in #261, the generated accessor `AContext.b()` has the wrong return type for the following grammar:

```antlr
grammar Test;

a : b? c d* d+ ;
b : ID;
c : ID;
d : ID;
e : ID;
```

### Expected signatures:

```typescript
export class AContext extends ParserRuleContext {
  b(): BContext | undefined;
  c(): CContext;
  d(): DContext[];
  d(i: number): DContext;
  e(): EContext[];
  e(i: number): EContext;
  // ...
}
```

### Actual signatures:

```typescript
export class AContext extends ParserRuleContext {
  b(): BContext;
  c(): CContext;
  d(): DContext[];
  d(i: number): DContext;
  e(): EContext[];
  e(i: number): EContext;
  // ...
}
```

### Difference we want to see (actual &rarr; expected)

```diff
 export class AContext extends ParserRuleContext {
-  b(): BContext;
+  b(): BContext | undefined;
   c(): CContext;
   d(): DContext[];
   d(i: number): DContext;
   e(): EContext[];
   e(i: number): EContext;
   // ...
 }
```

/cc @mike-lischke

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #265

@mike-lischke This should be a good start for you. 😄

### CODE REVIEW

**Comment by sharwell** [comment]
@mike-lischke One of the goals when working on this target was to use the type system accurately where possible. This includes avoiding the use of `any` where possible, and accurately representing the `undefined` and `null` types where possible. This pull request represents the latest work to address a previous inaccuracy in the context objects. It's not necessarily the final form, but I do intend to preserve/increase accuracy of the model if at all possible.

**Comment by mike-lischke** [comment]
Well, I'm more concerned about all the tryXX calls, because I cannot be sure if my grammar doesn't change (to) an optional token somewhere, in the future. I don't want to be forced to rework all my listeners when the grammar changes, just because the runtime tries to be super clever. However, when users like me always use tryGetChild all the time anyway, there is no need for a getChild() variant then. That separation seems so artificial.

But at the end it's your runtime, so we have to play by the rules you set. Not really a big deal, just a bit inconvenient.

**Comment by sharwell** [comment]
> I don't want to be forced to rework all my listeners when the grammar changes

If you do not rework your listeners following a grammar change, then you are likely going to hit a bug sooner or later. Over the course of time this was the dominant source of subtle regression bugs in applications I created using older versions of ANTLR. The [rule versioning](https://github.com/sharwell/antlr4/wiki/Rule-Versioning) feature is designed to simplify this process by documenting dependencies between code and the grammar, and forcing developers to review only affected code in listeners following a change in the grammar. I no longer develop applications without explicitly declaring dependencies ([example](https://github.com/tunnelvisionlabs/antlrworks2/blob/master/org-antlr-works-editor/src/org/antlr/works/editor/grammar/formatting/GrammarIndentTask.java#L446-L449)), and it provided *dramatic* short- and long-term wins.

**Comment by mike-lischke** [comment]
True, very good points.

**Comment by sharwell** [comment]
Note that I added the `RuleVersion` and `RuleDependency` types for use in the TypeScript target in #267 (will be in 0.4.0-alpha.3). Currently they don't perform validation but you can start using them for documentation purposes at that point.

**Pull request merged**
