### PR TITLE
Remove ATNState.serializationNames 

### PR DESCRIPTION
**Pull request by BurtHarris**
for debugging, per issue #282

### CODE REVIEW

**Comment by sharwell** [comment]
@BurtHarris Is there a reason we aren't implementing this by removing `const` from [`ATNStateType`](https://github.com/tunnelvisionlabs/antlr4ts/blob/master/src/atn/ATNStateType.ts#L8)?

**Comment by BurtHarris** [comment]
Thanks @sharwell.   Then I propose we simply remove the definition of `serializationNames`.     No need to remove `const` since we are using `--preserveConstEnums` in building.  

 There's was minor discrepancy in state-type 0 name, which now goes away.

**Comment by sharwell** [comment]
@BurtHarris The `--preserveConstEnums` keeps the names in source code, but it still won't allow you to use the enum that way in TypeScript code (unless something has changed in a newer version).

**Comment by BurtHarris** [comment]
I will split them up, but the other changes are a side-effect of implementing the latest `npm`, which applies some sort of cryptographic hash to validating the dependencies loaded.   Its seems like to be a very good thing.   I thought I had that in my commit message, but somehow lost it.

**Comment by BurtHarris** [comment]
@sharwell After further reading I understand why you suggested removing the `const` from [`ATNStateType`](https://github.com/tunnelvisionlabs/antlr4ts/blob/master/src/atn/ATNStateType.ts#L8).  would be good.   I *was* wrong about the impact of --preserveConstEnums.   I've just updated the branch this PR came from.

**Pull request merged**
