### PR TITLE
Update for compatability with latest verison of NPM

### PR DESCRIPTION
**Pull request by BurtHarris**
Running with NPM 6 started generating security warnings.   Nothing critical just that some of mocha's dependencies had vulnerabilities resolved by updates, so this updates Mocha too.   Also updates a few other devDependencies to pick up bug fix releases.

### CODE REVIEW

**Comment by sharwell** [comment]
I'll take a look at this one later today 👍

**Comment by BurtHarris** [comment]
Rebased for recent changes re tslint

**Comment by sharwell** [comment]
Something seriously broke here, but I'm implementing the change in a clean branch now

**Comment by sharwell** [comment]
@BurtHarris do you prefer I force push to your branch or close this and create a new pull request?

**Comment by sharwell** [comment]
Actually I'm thinking I'll create a new pull request since the change wasn't a simple rebase, but I'll reference this one since the work follows the same pattern.

**Pull request closed without merging**
