### PR TITLE
Inline sources into .js.map files

### LINKED ISSUE #432: Ship `.ts` sources or turn on `--inlineSources`
Hi there!

Today your package ships with `.js.map` files which redirect to `.ts` files that aren't included in the package. This ends up causing build tools (like Parcel) to spill out a ton of warnings.

```
‼  Could not load source file "../../../src/atn/BasicState.ts" in source map of "../node_modules/antlr4ts/atn/BasicState.js".
```

image

I would suggest either removing the sourcemaps entirely, or shipping the `src` directory as well.

### PR DESCRIPTION
**Pull request by BurtHarris**
Fixes #432 

Note: I don't currently have a working copy of Maven available to do the full build.   Submitting pull request to use cloud build for a test.

### CODE REVIEW

**Comment by BurtHarris** [comment]
@sharwell, something didn't go right with this.    Although it says the appveyor all checks passed, this page displays an error message I don't understand:  https://ci.appveyor.com/project/BurtHarris/antlr4ts/builds/29911485

**Comment by sharwell** [comment]
@BurtHarris Thanks I'll figure this out in a separate pull request

**Comment by sharwell** [comment]
@BurtHarris Here's the build for this pull request: https://ci.appveyor.com/project/sharwell/antlr4ts/builds/29911519

It looks like you're looking at the wrong AppVeyor build queue.

**Comment by BurtHarris** [comment]
OK.    I think the other build may have been when I checked it in to my branch.   I'm more than a little rusty on this.  

Without a working local build, I haven't verified this copies the typescript sources into the .js.map files.

I'll let you drive the merge and release as you see fit.  OK?

**Comment by BurtHarris** [comment]
I've added the fix for build issue to this PR

Fixes: #438

**Pull request merged**
